name: 'Run Android instrumentation tests'
author: 'emulator.wtf'
description: 'Run tests with emulator.wtf'
inputs:
  version:
    description: 'ew-cli version to use'
    required: true
    default: '0.0.47'
  api-token:
    description: 'Api token for emulator.wtf'
    required: true
  app:
    description: 'Application apk file'
    required: true
  test:
    description: 'Test apk file'
    required: true
  outputs-dir:
    description: 'Location to store test outputs in'
    required: false
  devices:
    description: 'Device configurations to use, in the form of model=X,version=Y per line'
    required: false
  use-orchestrator:
    description: 'Set to true to use the Android Test Orchestrator'
    required: false
  clear-package-data:
    description: 'Set to true to clear app data between every test (only works with orchestrator)'
    required: false
  with-coverage:
    description: 'Set to true to collect coverage files and save them to <outputs-dir>'
    required: false
  additional-apks:
    description: 'Additional apks to install, one per line'
    required: false
  environment-variables:
    description: 'Environment variables to pass to AndroidJUnitRunner, one per line in the form of key=value'
    required: false
  num-uniform-shards:
    description: 'Set to a number larger than 1 to randomly split your tests into multiple shards.'
    required: false
  num-shards:
    description: 'Set to a number larger than 1 to split your tests into even shards based on test count.'
    required: false
  directories-to-pull:
    description: 'Directories to pull from device and store in <outputs-dir>, one per line'
    required: false
branding:
  color: orange
  icon: smartphone
runs:
  using: composite
  steps:
    - name: Setup ew-cli
      uses: ubiratansoares/setup-ew-cli@ufs/node16
      with:
        version: ${{ inputs.version }}
    - name: Run instrumented tests
      uses: ubiratansoares/invoke@ufs/node16
      with:
        api-token: ${{ inputs.api-token }}
        app: ${{ inputs.app }}
        test: ${{ inputs.test }}
        outputs-dir: ${{ inputs.outputs-dir }}
        devices: ${{ inputs.devices }}
        use-orchestrator: ${{ inputs.use-orchestrator }}
        clear-package-data: ${{ inputs.clear-package-data }}
        with-coverage: ${{ inputs.with-coverage }}
        additional-apks: ${{ inputs.additional-apks }}
        environment-variables: ${{ inputs.environment-variables }}
        num-uniform-shards: ${{ inputs.num-uniform-shards }}
        num-shards: ${{ inputs.num-shards }}
        directories-to-pull: ${{ inputs.directories-to-pull }}
